M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu22.04.1} date 2023年12月12日 22時47分28秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-12T22:47:28+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X1.6Y-1.1
X1.9Y-1.2
X2.2Y-1.0
X2.2Y-1.4
T0
M30
